# Generated by Django 4.0.4 on 2022-05-11 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='women',
            old_name='cat',
            new_name='cat_id',
        ),
        migrations.RenameField(
            model_name='women',
            old_name='time_created',
            new_name='time_create',
        ),
        migrations.RenameField(
            model_name='women',
            old_name='time_updated',
            new_name='time_update',
        ),
    ]
